video_path: "/home/yigit/Desktop/zed_video_cikisi.mp4"

bev_settings:
  width: 600
  height: 800
  offset_x: 150.0

calibration:
  # ZED 2.2K Matrisi (Düz liste olarak - 3x3)
  camera_matrix: [1400.0, 0.0, 1104.0, 0.0, 1400.0, 621.0, 0.0, 0.0, 1.0]
  
  # Bozulma katsayıları (Düz liste)
  dist_coeffs: [0.0, 0.0, 0.0, 0.0, 0.0]

# Kaynak Noktalar (Numpy'nin kolay okuması için [x, y] listeleri halinde)
src_points:
  - [1078.0, 626.0]
  - [1218.0, 622.0]
  - [2064.0, 1148.0]
  - [428.0, 1148.0]
